version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0500
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: 0500
    volumes:
      - db_data:/var/lib/mysql

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - "8080:80"
    environment:
      NEXTCLOUD_ADMIN_USER: root
      NEXTCLOUD_ADMIN_PASSWORD: 0500
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: 0500
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - db

volumes:
  db_data:
  nextcloud_data:
