version: ''

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    volumes:
      - db_data:/var/lib/mysql

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - ""
    environment:
      NEXTCLOUD_ADMIN_USER: 
      NEXTCLOUD_ADMIN_PASSWORD: 
      MYSQL_HOST: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - db

volumes:
  db_data:
  nextcloud_data:
